name: transit
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - beautifulsoup4==4.12.3
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - gtfs-realtime-bindings==1.0.0
    - idna==3.6
    - numpy==1.26.4
    - pandas==2.2.1
    - protobuf==4.25.3
    - protobuf3-to-dict==0.1.5
    - python-dateutil==2.8.2
    - pytz==2024.1
    - requests==2.31.0
    - six==1.16.0
    - soupsieve==2.5
    - tzdata==2024.1
    - urllib3==2.2.1
